### ISSUE TITLE
Release branch

### ISSUE THREAD

**Issue by rollenes** [smsapi/smsapi-php-client#30]
I have some changes that I would like to merge, but those changes will break some interfaces. So those changes should be included in another version. In order to share and develop, release branch is required.
Can you create this branch?

**Comment by sudlik** [comment]
OK. I will create `1.2.1`, `1.3.0` and 2.0.0 branches.

**Comment by sudlik** [comment]
https://github.com/smsapi/smsapi-php-client/tree/1.2.1
https://github.com/smsapi/smsapi-php-client/tree/1.3.0
https://github.com/smsapi/smsapi-php-client/tree/2.0.0
