### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by f31n** [smsapi/smsapi-php-client#71]
i tried with token and password login - its not working i always get **Authorization failed** error;

then i tried with the curl version: https://www.smsapi.com/rest
that one is working like it should - couldn't trace the bug any further cause i actually didn't find the error in that package - so i guess its the answer form the server i'm talking to (also tried api2)

**Comment by smsapi** [comment]
Hello,
We have two services www.smsapi.pl and www.smsapi.com. It looks that you are using worng one.
Please write us an email: support@smsapi.com
Best regards,

**Comment by f31n** [comment]
correct, i checked the files according to that, in that case i have a wish for a feature improvement, check pl and com api & api2 if its working.

thanks for the quick answer.
