### ISSUE TITLE
Contact Edit returns Exception [contact_conflict] Contact already exists.

### ISSUE THREAD

**Issue by dudzio12** [smsapi/smsapi-php-client#77]
I'm getting customerId by actionContactList.
It returns hash, so I think it is correct value.
Later I'm trying to do: actionContactEdit.
I'm using contactId from above and then set other values.

After execute it's throwing Exception.
Please - check it as soon as possible.

**Comment by pdzieniszewski** [comment]
Please forward us your username on our platform by our site https://www.smsapi.pl/kontakt . Then we could verify it based on your requests to our API via library.
