### ISSUE TITLE
How to set encoding in smsApi.pl client?

### ISSUE THREAD

**Issue by jakubkoziara** [smsapi/smsapi-php-client#80]
Hi,
In previous version (1.8) It was possible to set custom encoding via `setEncoding()`.
In 2.0 via `SendSmsBag` there is no such function. I have problem with Polish characters. I saw only encoding property in SendSmsBag class. What can I do ?

**Comment by maciejlew** [comment]
Have you tried to set that property?

**Comment by jakubkoziara** [comment]
Yes, I tried with few methods. In this class there is only `set params` method which refers to `param1, param2, param3, param4` properties. If I set it directly in `public static function withMessage()` it works but it's not proper way. I also need to set `from` and other params.

**Comment by jakubkoziara** [comment]
Ok. I have hard to find bug in my code everything works fine. Thank You
