### ISSUE TITLE
Have no idea how to set encoding to UTF-8

### ISSUE THREAD

**Issue by shortcodes** [smsapi/smsapi-php-client#82]
Currently i tried to send a sms message with UTF-8 characters in polish language. Sms is being sended correctly but it has bushes instead of proper utf-8 characters. There is no place in this library documentation describing how to set it and i am feeling like the only one who is using this API. No one encounter this problem at this version??

**Comment by maciejlew** [comment]
Try to set SendSmsBag property:

```php
<?php

declare(strict_types=1);

use Smsapi\Client\Feature\Sms\Bag\SendSmsBag;

$sms = SendSmsBag::withMessage('someone phone number', 'some message');
$sms->encoding = 'utf-8';

```

**Comment by maciejlew** [comment]
Added to FAQ: [How to use optional request parameters?](https://github.com/smsapi/smsapi-php-client/blob/master/README.md#how-to-use-optional-request-parameters)

**Comment by shortcodes** [comment]
Excelent. It works! Thanks

**Comment by maciejlew** [comment]
UTF-8 is being set as default encoding starting from version 3.0.0. User do not have to set it explicitly.
