### ISSUE TITLE
DateTime::__construct() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by dudzio12** [smsapi/smsapi-php-client#91]
`DateTime::__construct() expects parameter 1 to be string, null given`

inside `\Smsapi\Client\Feature\Sms\Sendernames\Data\SendernameFactory:18`

When `$object->created_at` is null, an exception is thrown.

I'm actually using this package as a part of Magento integration module.

An easy fix is to check if `created_at` is not empty before using it as argument for DateTime object. I can make PR if you want to fix it that way and not by implementing changes inside Magento integration extension.

**Comment by maciejlew** [comment]
This issue was solved on API side.
