### ISSUE TITLE
Sending SMS triggers E_USER_DEPRECATED

### ISSUE THREAD

**Issue by rutek** [smsapi/smsapi-php-client#99]
Calling `SmsHttpFeature->sendSms(...)` triggers following deprecation error:

`E_USER_DEPRECATED: The path of a URI with an authority must start with a slash "/" or be empty. Automagically fixing the URI by adding a leading slash to the path is deprecated since version 1.4 and will throw an exception instead.`

It comes from `\GuzzleHttp\Psr7\Uri`. I think changing `SmsHttpFeature::makeRequest` to use `/sms.do` instead of `sms.do` will fix it.

Tested version: 3.0.2 on PHP 7.4. SMSAPI library automatically installed `guzzlehttp/psr7` in version 1.7.0.

**Comment by smsapi** [comment]
Hi @rutek. Thank you for information. We will verify that.

**Comment by vosecek** [comment]
Any progress? php library is not usable due to this problem.

**Comment by smsapi** [comment]
Thanks for the input! We know about this issue, and it is in our backlog since initially @rutek wrote about it. We intend to fix it, however it could still take some time.

**Comment by bbprojectnet** [comment]
Same issue here, any chance to fix it?
